### ISSUE TITLE
Try SymSpell

### ISSUE THREAD

**Issue by stephengtuggy** [michaelachrisco/subreddit-recommender#30]
Have you thought of trying https://github.com/PhilT/symspell, a Ruby port of a Faroo algorithm (http://blog.faroo.com/2012/06/24/1000x-faster-spelling-correction-source-code-released/)?

**Comment by michaelachrisco** [comment]
Looks interesting. We would have to see if the Damerau-Levenshtein distance algorithm is applicable to this project or not.

**Comment by stephengtuggy** [comment]
I was trying to come up with ways to make the subreddits:relate process faster. Now that I think about it, though, Apache Lucene/Solr would probably work better. I just created a separate issue for that.

**Comment by michaelachrisco** [comment]
Sounds good. On another note, It would be cool to add additional algorithms that may give us more incite on different relations between subreddits.
